language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

env:
  global:
    - setup=basic

sudo: false

before_install:
  - travis_retry composer self-update

install:
  - composer install --no-interaction

script: vendor/bin/phpunit